---
# tasks file for rails

- name: "Update RubyGems system software"
  command: /usr/local/bin/gem update --system --force
  become: true
  register: gem_update_system_result

- name: 'Delete existing rake to prevent hang due to conflict'
  file: path=/usr/local/bin/rake state=absent
  become: true

- name: 'Delete existing ri to prevent hang due to conflict'
  file: path=/usr/local/bin/ri state=absent
  become: true

- name: 'Delete existing rdoc to prevent hang due to conflict'
  file: path=/usr/local/bin/rdoc state=absent
  become: true

- name: 'print fucktarded warning about bug #14'
  debug: "msg='NOTE if the automation hangs on the next
          step, it is a bug, so kill it, SSH in as root,
          and manually do
          sudo /usr/local/bin/gem install pg -- --with-pg-config=/usr/pgsql-9.4/bin/pg_config && sudo /usr/local/bin/gem update
          It then should not happen the next time.

          See https://github.com/RobertReidInc/rollerball/issues/14
          for more info.'"

          # FIXME: this is a fuckin travesty and adds many seconds to role execution... fix it someday soon?

- name: "Update installed gems"
  command: /usr/local/bin/gem update --no-ri --no-rdoc --force
  become: true
  register: gem_update_result
  #  async: 5
  #  poll: 1
  # This hangs sometimes, waiting for input ("replace rdoc binary?"), see:
  # Provisioning automation hangs at 'gem update' #14
  # https://github.com/RobertReidInc/rollerball/issues/14
  # Hence all this fuckery in this section.

- debug: var=gem_update_result

- name: "Manually reinstall rake"
  command: /usr/local/bin/gem install rake --no-ri --no-rdoc
  become: true

- name: "Manually reinstall rdoc"
  command: /usr/local/bin/gem install rdoc --no-ri --no-rdoc
  become: true

- name: "Get currently installed Rails version (if any)"
  command: rails -v
  become: false
  register: rails_version_check
  ignore_errors: true
  failed_when: False

- name: "Install the latest Rails"
  command: /usr/local/bin/gem install rails --version {{ rails_version }}
  become: true
  register: rails_install_result
  when: rails_version_check.rc !=0 or not rails_version in rails_version_check.stdout
