---
# tasks file for mason-linux-core

- name: "Update all installed packages"
  yum: name=* state=latest
  register: yum_update_result
  become: true

- name: "Enable EPEL package repository"
  yum: name=epel-release state=latest
  become: true
  # This is needed for nodejs: https://fedoraproject.org/wiki/EPEL

- name: "Install various prerequisite packages with yum"
  yum: pkg={{item}} state=installed
  with_items:
    - autoconf
    - automake
    - bison
    - byobu
    - bzip2
    - curl
    - gcc-c++
    - git
    - ImageMagick
    - kernel-devel
    - kernel-headers
    - libffi-devel
    - libtool
    - libyaml-devel
    - lsof
    - make
    - nodejs
    - openssl-devel
    - patch
    - readline
    - readline-devel
    - sqlite-devel
    - vim
    - zlib
    - zlib-devel
  become: true

- name: "Set time zone to {{ time_zone }}"
  command: timedatectl set-timezone {{ time_zone }}
  become: true

