---
# tasks file for firewall-allows-web-traffic

- stat: path=/usr/bin/firewall-cmd
  register: firewalld_is_installed

- debug: var=firewalld_is_installed

- block:
  - name: 'Install firewalld'
    yum: pkg=firewalld state=installed
    become: true

  - name: "Enable and restart firewalld service on boot"
    service: name=firewalld enabled=yes state=restarted
    become: true

  when: not firewalld_is_installed.stat.exists

- name: "firewall-cmd: open HTTP port 80"
  command: /usr/bin/firewall-cmd --permanent --add-service http
  become: true

- name: "firewall-cmd: open port 3000 (for manual rails & byebug)"
  command: /usr/bin/firewall-cmd --permanent --add-port=3000/tcp
  become: true
  # actually this is useful on AWS too. when: server_type == 'vmware-fusion'

- name: "firewall-cmd: open HTTPS port 443"
  command: /usr/bin/firewall-cmd --permanent --add-service https
  become: true

- name: "firewall-cmd: reload"
  command: /usr/bin/firewall-cmd --reload
  become: true
